/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.CheckDados;
import classes.Cliente;
import classes.Produto;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    public CadastroCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTituloProduto = new javax.swing.JLabel();
        jlNomeCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jlEmailCliente = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        jlCpfCliente = new javax.swing.JLabel();
        txtCpfCliente = new javax.swing.JFormattedTextField();
        jlSenhaCliente = new javax.swing.JLabel();
        txtSenhaCliente = new javax.swing.JPasswordField();
        jlDataNascimentoCliente = new javax.swing.JLabel();
        txtDataNascimentoCliente = new javax.swing.JFormattedTextField();
        jlTelefoneCliente = new javax.swing.JLabel();
        txtTelefoneCliente = new javax.swing.JFormattedTextField();
        jlEnderecoCliente = new javax.swing.JLabel();
        txtEnderecoCliente = new javax.swing.JTextField();
        btnCancelarCliente = new javax.swing.JButton();
        btnAdicionarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Produto");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_uaifood.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(234, 29, 44));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 640));

        jlTituloProduto.setFont(new java.awt.Font("Sul Sans", 0, 24)); // NOI18N
        jlTituloProduto.setForeground(new java.awt.Color(255, 255, 255));
        jlTituloProduto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTituloProduto.setText("Novo Cliente");

        jlNomeCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlNomeCliente.setText("Nome:");

        txtNomeCliente.setBackground(new java.awt.Color(234, 29, 44));
        txtNomeCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        txtNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jlEmailCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlEmailCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlEmailCliente.setText("Email:");

        txtEmailCliente.setBackground(new java.awt.Color(234, 29, 44));
        txtEmailCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        txtEmailCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtEmailCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jlCpfCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlCpfCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlCpfCliente.setText("CPF:");

        txtCpfCliente.setBackground(new java.awt.Color(234, 29, 44));
        txtCpfCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        txtCpfCliente.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtCpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N

        jlSenhaCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlSenhaCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlSenhaCliente.setText("Senha:");

        txtSenhaCliente.setBackground(new java.awt.Color(234, 29, 44));
        txtSenhaCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        txtSenhaCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtSenhaCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        jlDataNascimentoCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlDataNascimentoCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlDataNascimentoCliente.setText("Data de nascimento:");

        txtDataNascimentoCliente.setBackground(new java.awt.Color(234, 29, 44));
        txtDataNascimentoCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        txtDataNascimentoCliente.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtDataNascimentoCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimentoCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        txtDataNascimentoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataNascimentoClienteFocusLost(evt);
            }
        });
        txtDataNascimentoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoClienteActionPerformed(evt);
            }
        });

        jlTelefoneCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlTelefoneCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlTelefoneCliente.setText("Telefone:");

        txtTelefoneCliente.setBackground(new java.awt.Color(234, 29, 44));
        txtTelefoneCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        txtTelefoneCliente.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtTelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N

        jlEnderecoCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlEnderecoCliente.setForeground(new java.awt.Color(255, 255, 255));
        jlEnderecoCliente.setText("Endereço (Bairro):");

        txtEnderecoCliente.setBackground(new java.awt.Color(234, 29, 44));
        txtEnderecoCliente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        txtEnderecoCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtEnderecoCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        btnCancelarCliente.setBackground(new java.awt.Color(234, 29, 44));
        btnCancelarCliente.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        btnCancelarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_fechar_branco.png"))); // NOI18N
        btnCancelarCliente.setText("Cancelar");
        btnCancelarCliente.setBorder(null);
        btnCancelarCliente.setBorderPainted(false);
        btnCancelarCliente.setContentAreaFilled(false);
        btnCancelarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClienteActionPerformed(evt);
            }
        });

        btnAdicionarCliente.setBackground(new java.awt.Color(234, 29, 44));
        btnAdicionarCliente.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        btnAdicionarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_adicionar_branco.png"))); // NOI18N
        btnAdicionarCliente.setText("Adicionar");
        btnAdicionarCliente.setBorder(null);
        btnAdicionarCliente.setBorderPainted(false);
        btnAdicionarCliente.setContentAreaFilled(false);
        btnAdicionarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(179, 179, 179)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlTelefoneCliente)
                                .addComponent(txtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlTituloProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(txtEmailCliente)
                                .addComponent(jlEmailCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(txtSenhaCliente)
                                .addComponent(jlSenhaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(txtEnderecoCliente)
                                .addComponent(jlEnderecoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(txtNomeCliente)
                                .addComponent(jlNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(jlCpfCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                .addComponent(txtDataNascimentoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlDataNascimentoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCpfCliente))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnCancelarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionarCliente)))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jlTituloProduto)
                .addGap(43, 43, 43)
                .addComponent(jlNomeCliente)
                .addGap(6, 6, 6)
                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jlEmailCliente)
                .addGap(6, 6, 6)
                .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlCpfCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSenhaCliente)
                .addGap(6, 6, 6)
                .addComponent(txtSenhaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefoneCliente)
                    .addComponent(jlDataNascimentoCliente))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jlEnderecoCliente)
                .addGap(6, 6, 6)
                .addComponent(txtEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataNascimentoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoClienteActionPerformed
        
    }//GEN-LAST:event_txtDataNascimentoClienteActionPerformed

    private void btnCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarClienteActionPerformed

    private void btnAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarClienteActionPerformed
        
        String nome = txtNomeCliente.getText();
        String email = txtEmailCliente.getText();
        String cpf = txtCpfCliente.getText().replaceAll("[\\D]", ""); // filtra os digitos
        String senha = txtSenhaCliente.getText();
        String telefone = txtTelefoneCliente.getText().replaceAll("[\\D]", ""); // filtra os digitos
        String endereco = txtEnderecoCliente.getText();
        String dataDeNascimento = txtDataNascimentoCliente.getText();
        
        // Checar se os campos estão vazios
        if (CheckDados.ehVazio(nome,email,cpf,senha,telefone,dataDeNascimento)) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Checar se a data de nascimento está errada
        if (CheckDados.checaData(dataDeNascimento)){
            JOptionPane.showMessageDialog(null, "Data de nascimento inválida!", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        /*
        try {
            // CHECAR A PREEXISTENCIA DO CPF
            if (CheckDados.checaCpf(cpf)){
                JOptionPane.showMessageDialog(null, "CPF já existente!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (IOException ex) {
            Logger.getLogger(CadastrarMotoboy.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        
        Cliente cliente = new Cliente(0, endereco, cpf, nome, email, senha, dataDeNascimento, telefone);
        try {
            cliente.init();
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso.", "Sucesso!", JOptionPane.PLAIN_MESSAGE);
            this.setVisible(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Algo deu errado! O cliente não foi cadastrado.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAdicionarClienteActionPerformed

    private void txtDataNascimentoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataNascimentoClienteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoClienteFocusLost

    public void checkBirthDate() {
        // TODO add your handling code here:
        // CHECAR se a data é correta
        String dataJoin = txtDataNascimentoCliente.getText();
        String dateFormat = "dd/MM/uuuu";

        DateTimeFormatter dateTimeFormatter = DateTimeFormatter
            .ofPattern(dateFormat)
            .withResolverStyle(ResolverStyle.STRICT);

        // Se a data estiver errada, da um erro que pode ser pego pelo try..catch
        LocalDate date = LocalDate.parse(dataJoin, dateTimeFormatter);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCliente;
    private javax.swing.JButton btnCancelarCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlCpfCliente;
    private javax.swing.JLabel jlDataNascimentoCliente;
    private javax.swing.JLabel jlEmailCliente;
    private javax.swing.JLabel jlEnderecoCliente;
    private javax.swing.JLabel jlNomeCliente;
    private javax.swing.JLabel jlSenhaCliente;
    private javax.swing.JLabel jlTelefoneCliente;
    private javax.swing.JLabel jlTituloProduto;
    private javax.swing.JFormattedTextField txtCpfCliente;
    private javax.swing.JFormattedTextField txtDataNascimentoCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtEnderecoCliente;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JPasswordField txtSenhaCliente;
    private javax.swing.JFormattedTextField txtTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
