/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Motoboy;
import classes.Produto;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class CadastrarMotoboy extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    public CadastrarMotoboy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jlTituloMotoboy = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jlCpf = new javax.swing.JLabel();
        btnNovoMotoboy = new javax.swing.JButton();
        btnNovoProduto1 = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jlSenha = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jlComissao = new javax.swing.JLabel();
        txtDataDeNascimento = new javax.swing.JFormattedTextField();
        txtComecoExpediente = new javax.swing.JFormattedTextField();
        txtFimExpediente = new javax.swing.JFormattedTextField();
        jlExpediente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Produto");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_uaifood.png")).getImage());
        setResizable(false);

        jScrollPane1.setMinimumSize(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(360, 640));

        jPanel1.setBackground(new java.awt.Color(234, 29, 44));
        jPanel1.setMinimumSize(new java.awt.Dimension(343, 638));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTituloMotoboy.setFont(new java.awt.Font("Sul Sans", 0, 24)); // NOI18N
        jlTituloMotoboy.setForeground(new java.awt.Color(255, 255, 255));
        jlTituloMotoboy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTituloMotoboy.setText("Cadastrar Motoboy");
        jPanel1.add(jlTituloMotoboy, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 30, 310, -1));

        jlNome.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlNome.setForeground(new java.awt.Color(255, 255, 255));
        jlNome.setText("Nome:");
        jPanel1.add(jlNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 85, -1, -1));

        txtNome.setBackground(new java.awt.Color(234, 29, 44));
        txtNome.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 106, 310, 38));

        jlEmail.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlEmail.setForeground(new java.awt.Color(255, 255, 255));
        jlEmail.setText("Email:");
        jPanel1.add(jlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 155, -1, -1));

        txtTelefone.setBackground(new java.awt.Color(234, 29, 44));
        txtTelefone.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 385, 310, 38));

        jlCpf.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlCpf.setForeground(new java.awt.Color(255, 255, 255));
        jlCpf.setText("CPF:");
        jPanel1.add(jlCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 225, -1, -1));

        btnNovoMotoboy.setBackground(new java.awt.Color(234, 29, 44));
        btnNovoMotoboy.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        btnNovoMotoboy.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoMotoboy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_adicionar_branco.png"))); // NOI18N
        btnNovoMotoboy.setText("Adicionar");
        btnNovoMotoboy.setBorder(null);
        btnNovoMotoboy.setBorderPainted(false);
        btnNovoMotoboy.setContentAreaFilled(false);
        btnNovoMotoboy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoMotoboy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoMotoboyActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovoMotoboy, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 120, 38));

        btnNovoProduto1.setBackground(new java.awt.Color(234, 29, 44));
        btnNovoProduto1.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        btnNovoProduto1.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoProduto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_fechar_branco.png"))); // NOI18N
        btnNovoProduto1.setText("Cancelar");
        btnNovoProduto1.setBorder(null);
        btnNovoProduto1.setBorderPainted(false);
        btnNovoProduto1.setContentAreaFilled(false);
        btnNovoProduto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProduto1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovoProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 120, 38));

        txtEmail.setBackground(new java.awt.Color(234, 29, 44));
        txtEmail.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 176, 310, 38));

        jlSenha.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlSenha.setForeground(new java.awt.Color(255, 255, 255));
        jlSenha.setText("Senha:");
        jPanel1.add(jlSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 295, -1, -1));

        jlTelefone.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jlTelefone.setText("Telefone:");
        jPanel1.add(jlTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 365, -1, -1));

        txtSenha.setBackground(new java.awt.Color(234, 29, 44));
        txtSenha.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        txtSenha.setForeground(new java.awt.Color(255, 255, 255));
        txtSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        txtSenha.setSelectionColor(new java.awt.Color(160, 35, 49));
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 316, 310, 38));

        jlComissao.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlComissao.setForeground(new java.awt.Color(255, 255, 255));
        jlComissao.setText("Data de Nascimento:");
        jPanel1.add(jlComissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 435, -1, -1));

        txtDataDeNascimento.setBackground(new java.awt.Color(234, 29, 44));
        txtDataDeNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        txtDataDeNascimento.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtDataDeNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataDeNascimento.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        txtDataDeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataDeNascimentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDataDeNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 456, 310, 40));

        txtComecoExpediente.setBackground(new java.awt.Color(234, 29, 44));
        txtComecoExpediente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        txtComecoExpediente.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtComecoExpediente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtComecoExpediente.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        txtComecoExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComecoExpedienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtComecoExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 528, 140, 40));

        txtFimExpediente.setBackground(new java.awt.Color(234, 29, 44));
        txtFimExpediente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        txtFimExpediente.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtFimExpediente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFimExpediente.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        jPanel1.add(txtFimExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 528, 140, 40));

        jlExpediente.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlExpediente.setForeground(new java.awt.Color(255, 255, 255));
        jlExpediente.setText("Expediente:");
        jPanel1.add(jlExpediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 507, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 20, 40));

        txtCpf.setBackground(new java.awt.Color(234, 29, 44));
        txtCpf.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        txtCpf.setForeground(new java.awt.Color(255, 255, 255));
        txtCpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 246, 310, 38));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProduto1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnNovoProduto1ActionPerformed

    private void btnNovoMotoboyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoMotoboyActionPerformed
        // TODO add your handling code here:
        if (txtNome.getText().equals("")
            || txtTelefone.getText().equals("")
            || txtEmail.getText().equals("")
            || txtCpf.getText().equals("")
            || String.valueOf(txtSenha.getPassword()).equals("")
            || txtTelefone.getText().equals("")
            || txtDataDeNascimento.getText().equals("")
            || txtComecoExpediente.getText().equals("")
            || txtFimExpediente.getText().equals("")
        ) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String nome = txtNome.getText();
        String email = txtEmail.getText();
        String cpf = txtCpf.getText();
        String senha = String.valueOf(txtSenha.getPassword());
        String telefone = txtTelefone.getText();
        String dataDeNascimento = txtDataDeNascimento.getText();
        String comecoExpediente = txtComecoExpediente.getText();
        String fimExpediente = txtFimExpediente.getText();
        
        try {
            Motoboy motoboy = new Motoboy(0, 0.1f, true, cpf, nome, email, senha, dataDeNascimento, telefone);
            motoboy.init();
            JOptionPane.showMessageDialog(null, "Motoboy cadastrado com sucesso.", "Sucesso!", JOptionPane.PLAIN_MESSAGE);
            this.setVisible(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Algo deu errado! O motoboy não foi cadastrado.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNovoMotoboyActionPerformed

    private void txtDataDeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataDeNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataDeNascimentoActionPerformed

    private void txtComecoExpedienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComecoExpedienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComecoExpedienteActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarMotoboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarMotoboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarMotoboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarMotoboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarMotoboy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoMotoboy;
    private javax.swing.JButton btnNovoProduto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlComissao;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlExpediente;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlTituloMotoboy;
    private javax.swing.JFormattedTextField txtComecoExpediente;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataDeNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtFimExpediente;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
