/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.ManipuladorArquivo;
import classes.Motoboy;
import classes.Produto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */

class MyComboBoxModel extends DefaultComboBoxModel<String> {
    public MyComboBoxModel(String[] items) {
        super(items);
    }
 
    @Override
    public String getSelectedItem() {
        String selectedString = (String) super.getSelectedItem();
 
        return selectedString;
    }
}

public class ExcluirMotoboy extends javax.swing.JFrame {
    private ArrayList<Motoboy> motoboys;
    
    /**
     * Creates new form CadastroProduto
     */
    public ExcluirMotoboy() {
        initComponents();
        
        carregarMotoboys();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSelecionarProduto = new javax.swing.JPanel();
        cmbMotoboy = new javax.swing.JComboBox<>();
        jlDescricaoMotoboy = new javax.swing.JLabel();
        btnNovoMotoboy = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Excluir Motoboy");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_uaifood.png")).getImage());
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpSelecionarProduto.setBackground(new java.awt.Color(234, 29, 44));
        jpSelecionarProduto.setMaximumSize(null);
        jpSelecionarProduto.setPreferredSize(new java.awt.Dimension(360, 640));

        cmbMotoboy.setFont(new java.awt.Font("Sul Sans", 0, 13)); // NOI18N
        cmbMotoboy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlDescricaoMotoboy.setFont(new java.awt.Font("Sul Sans", 0, 14)); // NOI18N
        jlDescricaoMotoboy.setForeground(new java.awt.Color(255, 255, 255));
        jlDescricaoMotoboy.setText("Selecione um motoboy:");

        btnNovoMotoboy.setBackground(new java.awt.Color(234, 29, 44));
        btnNovoMotoboy.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        btnNovoMotoboy.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoMotoboy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_fechar_branco.png"))); // NOI18N
        btnNovoMotoboy.setText("Excluir");
        btnNovoMotoboy.setBorder(null);
        btnNovoMotoboy.setBorderPainted(false);
        btnNovoMotoboy.setContentAreaFilled(false);
        btnNovoMotoboy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovoMotoboy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoMotoboyActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(234, 29, 44));
        btnVoltar.setFont(new java.awt.Font("Sul Sans", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_voltar_branco.png"))); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setBorder(null);
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSelecionarProdutoLayout = new javax.swing.GroupLayout(jpSelecionarProduto);
        jpSelecionarProduto.setLayout(jpSelecionarProdutoLayout);
        jpSelecionarProdutoLayout.setHorizontalGroup(
            jpSelecionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSelecionarProdutoLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jpSelecionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnNovoMotoboy, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(cmbMotoboy, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlDescricaoMotoboy, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(53, 53, 53))
        );
        jpSelecionarProdutoLayout.setVerticalGroup(
            jpSelecionarProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSelecionarProdutoLayout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(jlDescricaoMotoboy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbMotoboy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovoMotoboy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );

        getContentPane().add(jpSelecionarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoMotoboyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoMotoboyActionPerformed
        // TODO add your handling code here:
        if (cmbMotoboy.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um produto.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int indice_motoboy = cmbMotoboy.getSelectedIndex() - 1;
        Motoboy motoboy = motoboys.get(indice_motoboy);

            try {
            ManipuladorArquivo.excluir(motoboy);
            JOptionPane.showMessageDialog(null, "Motoboy excluído com sucesso.", "Sucesso!", JOptionPane.PLAIN_MESSAGE);
            
            carregarMotoboys();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Algo deu errado! O motoboy não foi excluído.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNovoMotoboyActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirMotoboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirMotoboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirMotoboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirMotoboy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirMotoboy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoMotoboy;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cmbMotoboy;
    private javax.swing.JLabel jlDescricaoMotoboy;
    private javax.swing.JPanel jpSelecionarProduto;
    // End of variables declaration//GEN-END:variables

    private void carregarMotoboys() {
        try {
            motoboys = ManipuladorArquivo.carregarMotoboys();
            ArrayList<String> nomes_motoboys = new ArrayList();
            
            nomes_motoboys.add("Selecione um motoboy");
            for (Motoboy motoboy : motoboys) {
                nomes_motoboys.add(String.valueOf(motoboy.getCodMotoboy()) + " - " + motoboy.getNome());
            }
            
            MyComboBoxModel myModel = new MyComboBoxModel(nomes_motoboys.toArray(new String[0]));
            cmbMotoboy.setModel(myModel);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao carregar os motoboys!", "Erro", JOptionPane.PLAIN_MESSAGE);
        }
    }
}
